[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.19"

[rpc_endpoints]
base_goerli = "https://goerli.base.org"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config